apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: my-express-app
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30100
