apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: postgres-operator
spec:
  selector:
    app.kubernetes.io/name: keycloak
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
